### ISSUE TITLE
atob issue nginx

### ISSUE THREAD

**Issue by chrisdotcollins** [stuicey/SSHy#18]
Hi,

I've successfully tested SSHy in a test environment, but when rolling out to my real system, I'm running into the following issue (IP obfuscated) in the javascript console on my browser:

Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at WebSocket.ws.onmessage (http://10.20.30.40/sshy/js/combinedJS.comb.js:381:240)
ws.onmessage @ combinedJS.comb.js:381

The connection comes through wsproxy ok as I see the following on my console:

$ wsproxy
[Status]: Starting wsProxy on port 5999...
[Info]: Requested connection from '::ffff:20.30.40.50' to '10.20.30.40:22' [ACCEPTED].
[Status]: Connection accepted from '10.20.30.40:22'.

But nothing happens on the webpage (using wrapper) or I just get a connection attempt (index). Eventually it seems to time out as I see a connection closed message on the wsproxy console output.

I've tried adding additional console.log to parceler.js as advised on another ticket to see increased logging of comms between server and client, but I see nothing at all.

I'm pretty sure I've replicated the (minimal) config between test and real.

Any ideas?

Thanks,

Chris

**Comment by stuicey** [comment]
Hi Chris,

What web browser are you using? The most likely causes I can see at the moment is either your web browser isn't properly dealing with the base64 string or your SSH server is supplying some dodgy identification string.

Since you're using the wrapper you'll need to edit `js/SSHyClient.js` to get additional debugging and recompile the JS with:
`java -jar closure-compiler.jar --js_output_file=js/combinedJS.comb.js js/defines.js js/src/*.js js/*.js '!**.comb.js'`

I'd recommend adding a `console.log(e.data)` to [here](https://github.com/stuicey/SSHy/blob/master/js/SSHyClient.js#L133) which will log the base64 encoded string to the console. The first message received will be the server identification string and should resolve to something like this:
`SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u3`

If you could paste the base64 encoded string here I can look into why it isn't being decoded properly.

**Comment by chrisdotcollins** [comment]
Thanks for following up 

I don't think it is browser based, as I can connect to my working test setup on the same (chrome btw) browser that fails when trying to connect on the real setup.

When I add in the console.log line, on the javascript console is an additional info message:
 Blob(21) {size: 21, type: ""}

I've looked through this, but can't see anything too obvious regarding the SSH identification string.

If I set up a debug SSH server and point wrapper.html at it, I can see the initial connection, but thats as far as it goes:

```
debug3: fd 5 is not O_NONBLOCK
debug1: Server will not fork when running in debugging mode.
debug3: send_rexec_state: entering fd = 8 config len 715
debug3: ssh_msg_send: type 0
debug3: send_rexec_state: done
debug1: rexec start in 5 out 5 newsock 5 pipe -1 sock 8
debug1: inetd sockets after dupping: 3, 3
Connection from blah port 49428 on blah port 2200

```
If I do a verbose connection from the command line, I get the following sort of info:

```
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 58: Applying options for *
debug1: /etc/ssh/ssh_config line 69: Deprecated option "useroaming"
debug2: resolving "localhost" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to localhost [127.0.0.1] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /home/bob/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/bob/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/bob/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/bob/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/bob/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/bob/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/bob/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/bob/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: match: OpenSSH_7.4 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to localhost:22 as 'bob'
debug3: hostkeys_foreach: reading file "/home/bob/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/bob/.ssh/known_hosts:2
debug3: load_hostkeys: loaded 1 keys from localhost
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
etc
```

**Comment by stuicey** [comment]
That doesn't look right for what was logged in the console, it shouldn't be a binary blob that you received: `Blob(21) {size: 21, type: ""}`. 

It should have just been a plain string, which is probably why `atob()` is failing. Did you download the forked version of wsproxy that is linked to this repository as a sub-module? The original version doesn't have base64 support.

You could try [this](https://github.com/stuicey/SSHy/issues/4) code that someone else wrote if you want to try using binary blobs from websockify or another websocket proxy. I had thought about adding in support for both but had never got around to it.

**Comment by chrisdotcollins** [comment]
Well, sorry....I had installed the forked version as me, but it seems there was also a global install which I guess then wasn't the forked version. I had thought I'd deleted it previously, but having gone through a proper purge of them with multiple npm uninstalls and reinstalling the correct one, it 'magically' works!

Apologies and thanks very much...

**Comment by stuicey** [comment]
No worries 😄, glad you got it working

**Comment by tayler0101** [comment]
hi @stuicey 
i would like to ask you how i can install the forked version of wsProxy i have the exact same failure.
thank you in advance

**Comment by stuicey** [comment]
You can run the following from where SSHy is cloned to ( note the `/` telling NPM to install from the directory ):
```
git submodule update --init --recursive
npm i -g wsproxy/
wsproxy
```

OR

Clone [stuicey/wsproxy](https://github.com/stuicey/wsproxy) and run `npm i -g .` from where wsproxy is cloned to.

**Comment by tayler0101** [comment]
@stuicey 
thanks man it works, i have another question regarding replacing  the wsProxy with another technology, can i ask it here or new issue/question or email?
thanks in advance

**Comment by stuicey** [comment]
A new issue would be preferable

**Comment by movcale** [comment]
hello
the same issue for me, with SSHy on nginx :

> ws.onmessage = function(b) {
>         transport.parceler.handle(atob(b.data))
>     }

trying Chrome with result:
Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at WebSocket.ws.onmessage (http://site.url/js/combinedJS.comb.js:381:240)

and FireFox with result:
InvalidCharacterError: String contains an invalid character s:235 
startSSHy/ws.onmessage http://site.url/:235:31

wsProxy installed as docker container with Dockerfile:
FROM node
RUN npm install wsproxy -g

and then
docker build -t wsproxy .
docker run -ti --rm -p 5999:5999 wsproxy:latest wsproxy

I will try to build wsproxy from source, as described above....

**Comment by movcale** [comment]
It works if built from source. So please update README.
My docker files attached for reference.
[wsproxy_docker.zip](https://github.com/stuicey/SSHy/files/2808236/wsproxy_docker.zip)
