### ISSUE TITLE
Can i replace the websocket with webusb

### ISSUE THREAD

**Issue by tayler0101** [stuicey/SSHy#19]
HI,
so what i am tring to do is replace the websocket with the [Webusb](https://developers.google.com/web/updates/2016/03/access-usb-devices-on-the-web) connection,
the Webusb is going to handle the send and receive the data.
is there is any tips you can give me?

**Comment by stuicey** [comment]
Is there a specific reason you need to use webusb? I'm not familiar with its capabilities but I imagine you'd need some sort of proxy on the SSH server to interface between hardware and TCP stack.

If you really need to use webusb, I think you'd need to replace all the websocket functions with their webusb equivalent ( onmessage, send, new connection). Which would be easiest done with the wrapper by editing `js/SSHyClient.js` and recompiling, as the wrapper doesn't have IP validation. 

As long as there is an end-to-end method of communication between client and server it should work. The SSHy client expects and supplies data to be encoded as a string with the SSH headers and padding included.

**Comment by tayler0101** [comment]
Actually i have gateway (without hdmi or vga port so the only option is is to communicate through serial port with Webusb ) with linux on it, as in the other end (the gateway) i am simple port forwarding `socat` to forward all the packet from the serial port to ssh port.
I will try edit the js/SSHyClient.js and customize it to fit my request.
do you have plan to support the public key in ssh, i mean without password or it is already supported, sorry for some question if it look like silly questions

**Comment by stuicey** [comment]
Best of luck with that!

I haven't implemented public key yet, its something I'd like to do but haven't looked into yet.
