### ISSUE TITLE
JS Error 

### ISSUE THREAD

**Issue by ravermeister** [stuicey/SSHy#23]
Hi, 
I'm trying to set up SSHy, it's running behind Apache with ssl. 
I started the wsproxy with ssl support:
``
wsproxy -t 4 -a 127.0.0.1:22 -p 65173 -s -k /path/to/privkey.pem -c /path/to/certfile.pem
``
when I try to connect either via wrapper.html or index.html
I get a JS Error:
``
Firefox can’t establish a connection to the server at wss://localhost:65173/127.0.0.1:22.
TypeError: transport is undefined
``
what am I doing wrong?

**Comment by stuicey** [comment]
Hey,

Just to confirm, did you install wsproxy from my fork or via node?

http://github.com/stuicey/wsproxy 

Unless its been patched the original version hasn't been updated to function with the latest websocket revision.

**Comment by ravermeister** [comment]
I think it was via node not sure thanks I'll try With the one in the repo and report back

**Comment by ravermeister** [comment]
Ok, I double checked the wsproxy version, but still the same issue:  https://pastebin.com/eMef4TDA

**Comment by stuicey** [comment]
Its looking like the websocket connection isn't opening as `transport` is null until the websocket connection successfully opens:
```
ws.onopen = function(e) {
    transport = new SSHyClient.Transport(ws, settings);
    ...
}
```

Could you try running wsproxy without any arguments and see if that works? Curious whether its the SSL or something to do with the whitelisted IPs. You're not gaining much additional security using a certificate here anyway as the SSH connection is encrypted via JavaScript and  decrypted by the SSH server.

**Comment by ravermeister** [comment]
I think I  know why it can't work, I forgot that SSHy is delivered via Apache proxy, and so the wsproxy which runs on the same machine where the js files are served by the proxy is not reachable from outside, 
I have to rethink the architecture, or stick with shellinabox. 
Will close it for now, thanks for your help :)
