### ISSUE TITLE
Is there any way to include user name in wrapper.html?

### ISSUE THREAD

**Issue by jonsito** [stuicey/SSHy#35]
Hello!

I want to use SSHy in an student lab at dit.upm.es to allow students remote access to our resources without installing any app in their computers

The lab platform already performs an LDAP authentication, then choose an available host from lab and fires up an ssh console to that host via wrapper.
I wish to include in wrapper user name, to avoid re-enter it at login prompt (and thus avoiding change pre-authenticated user), that is just ask (again) for password before opening ssh session

Is this possible?
Thanks in advance
Juan Antonio

**Comment by stuicey** [comment]
Hey Juan,

Currently this isn't something that's supported but you might be able to get this behaviour if you added something like the following to `wrapper.html`

```js
function wrapper_auth(){
    if(typeof transport == 'undefined'){ 
        setTimeout(wrapper_auth, 150);
    } else { 
        transport.auth.termUsername = // injected_user
        term.write("\n\r" + transport.auth.termUsername + '@' + transport.auth.hostname + '\'s password:');
        transport.auth.termPassword = '';
    }  
}

wrapper_auth()
```

**Comment by jonsito** [comment]
Sadly it doesn't work: user is properly set, but term still ask for "Login as:" (no name shown)... need to press enter to ask for password ( where user name is shown )
Also, with this patch sometimes "term" is not yet initialized, thus script throws an error

Finally  I've solved it by mean of discarding wrapper.html, using index.html, injecting host and user in form and make those fields readonly

Thanks for your time
Juan Antonio
