### ISSUE TITLE
Question: Predefined commands?

### ISSUE THREAD

**Issue by Relix360** [stuicey/SSHy#37]
Is possible to generate buttons to run specific commands like service status, restart?

**Comment by stuicey** [comment]
Yeah you could if you wanted to, you'd just create a button that [sends a string to the SSH server](https://github.com/stuicey/SSHy/blob/master/js/transport.js#L371)

```js
// transport is defined as a global once the SSH connection starts
transport.expect_key('systemctl status')
```

You could get more advanced if you wanted and start using some custom parsing on the [results that come back](https://github.com/stuicey/SSHy/blob/master/js/transport.js#L162). 

_edit: as a note, you'll need to re-minify the project if you're changing any of the libraries_

**Comment by Relix360** [comment]
@stuicey  Tky for your help I will se what can i do
